import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {handleFinancialHelpPayments as handle} from './financial-help-payments.js';
const origin='https://www.suchawellness.com';
const campaign={id:'approved-person',mode:'live',published:true,paymentsEnabled:true,beneficiaryConfirmed:true,recipientName:'Approved recipient',title:'A livelihood',story:'Recipient-approved public story.',storyUrl:'https://example.org/story',targetAmount:50000};
const prefix='financial-help:live:approved-person:';
function environment(overrides={}) {
  const data=new Map([['financial-help:campaign',JSON.stringify(campaign)]]);
  return {data,RAZORPAY_KEY_ID:'rzp_live_fixture',RAZORPAY_KEY_SECRET:'unit-test-only',FINANCIAL_HELP_RAZORPAY_WEBHOOK_SECRET:'webhook-test-only',FEEDBACK_KV:{get:async(key,options)=>{const value=data.get(key);return options?.type==='json'?(value?JSON.parse(value):null):(value || null)},put:async(key,value)=>data.set(key,value),list:async({prefix})=>({keys:[...data.keys()].filter(key=>key.startsWith(prefix)).map(name=>({name})),list_complete:true})},...overrides};
}
const request=(action,body,headers={})=>new Request(origin+'/api/financial-help/'+action,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...headers},...(body?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});
const signature=(message,secret='unit-test-only')=>createHmac('sha256',secret).update(message).digest('hex');
const proof=()=>({razorpay_order_id:'order_123',razorpay_payment_id:'pay_123',razorpay_signature:signature('order_123|pay_123')});
const savedOrder={orderId:'order_123',publicId:'public-123',campaignId:campaign.id,amountMinor:50000,currency:'INR',displayName:'Anonymous',createdAt:'2026-09-23T00:00:00.000Z'};
function withOrder(env){env.data.set(prefix+'order:order_123',JSON.stringify(savedOrder));return env}
function provider(t,overrides={}) {t.mock.method(globalThis,'fetch',async()=>Response.json({id:'pay_123',order_id:'order_123',amount:50000,currency:'INR',status:'captured',captured:true,amount_refunded:0,...overrides}));}
test('no real campaign closes checkout without exposing secrets',async()=>{const env=environment();env.data.clear();assert.deepEqual(await (await handle(request('config'),env)).json(),{available:false,campaign:null});assert.equal((await handle(request('create-checkout',{amount:500}),env)).status,503)});
test('unconfirmed recipient or wrong-mode keys disable checkout',async()=>{const env=environment();env.data.set('financial-help:campaign',JSON.stringify({...campaign,beneficiaryConfirmed:false}));assert.equal((await (await handle(request('config'),env)).json()).available,false);env.data.set('financial-help:campaign',JSON.stringify(campaign));env.RAZORPAY_KEY_ID='rzp_test_fixture';assert.equal((await handle(request('create-checkout',{amount:500}),env)).status,503)});
test('rejects unsafe story links',async()=>{const env=environment();env.data.set('financial-help:campaign',JSON.stringify({...campaign,storyUrl:'javascript:alert(1)'}));assert.equal((await (await handle(request('config'),env)).json()).campaign,null)});
test('validates amount, campaign and same-origin requests',async()=>{const env=environment();for(const amount of [0,-5,10.5,'500',100001])assert.equal((await handle(request('create-checkout',{campaignId:campaign.id,amount,anonymous:true}),env)).status,400);assert.equal((await handle(request('create-checkout',{campaignId:'fake',amount:500,anonymous:true}),env)).status,404);assert.equal((await handle(request('create-checkout',{amount:500},{Origin:'https://evil.example'}),env)).status,403)});
test('order uses server currency/fee policy and honors anonymity',async t=>{const env=environment();t.mock.method(globalThis,'fetch',async(url,options)=>{const body=JSON.parse(options.body);assert.equal(body.amount,50000);assert.equal(body.currency,'INR');assert.equal(body.notes.campaign_id,campaign.id);assert.ok(!JSON.stringify(body).includes('Private name'));return Response.json({id:'order_123',amount:50000,currency:'INR'})});const res=await handle(request('create-checkout',{campaignId:campaign.id,amount:500,anonymous:true,displayName:'Private name',feeMinor:0,currency:'USD'}),env);assert.equal(res.status,200);assert.equal(JSON.parse(env.data.get(prefix+'order:order_123')).displayName,'Anonymous')});
test('invalid signatures never record contributions',async()=>{const env=withOrder(environment());assert.equal((await handle(request('verify-checkout',{...proof(),razorpay_signature:'0'.repeat(64)}),env)).status,403);assert.equal(env.data.has(prefix+'payment:pay_123'),false)});
test('captured verified payment is idempotent with 90/10 split and no delivery claim',async t=>{provider(t);const env=withOrder(environment());for(let i=0;i<2;i++){const res=await handle(request('verify-checkout',proof()),env);assert.equal(res.status,200);const {contribution}=await res.json();assert.equal(contribution.amountMinor,50000);assert.equal(contribution.feeMinor,5000);assert.equal(contribution.recipientMinor,45000);assert.equal(contribution.deliveryStatus,'not_transferred');assert.equal(contribution.mode,'live')}assert.equal([...env.data.keys()].filter(key=>key.includes(':payment:')).length,1);const ledger=await (await handle(request('contributions'),env)).text();assert.ok(!ledger.includes('pay_123'));assert.ok(!ledger.includes('order_123'));assert.ok(!ledger.includes('unit-test-only'))});
for(const [name,change,status] of [['authorized',{status:'authorized',captured:false},409],['wrong amount',{amount:100},403],['wrong currency',{currency:'USD'},403],['wrong order',{order_id:'order_other'},403],['refunded',{amount_refunded:50000},409]])test('rejects '+name+' payment',async t=>{provider(t,change);assert.equal((await handle(request('verify-checkout',proof()),withOrder(environment()))).status,status)});
test('webhook checks raw signature and recovers captured contribution',async t=>{provider(t);const env=withOrder(environment());const raw=JSON.stringify({event:'payment.captured',payload:{payment:{entity:{id:'pay_123',order_id:'order_123'}}}});assert.equal((await handle(request('webhook',raw,{'X-Razorpay-Signature':'0'.repeat(64)}),env)).status,403);const signed={'X-Razorpay-Signature':signature(raw,'webhook-test-only')};assert.equal((await handle(request('webhook',raw,signed),env)).status,200);assert.equal((await handle(request('webhook',raw,signed),env)).status,200);assert.equal([...env.data.keys()].filter(key=>key.includes(':payment:')).length,1)});
test('oversized and malformed requests fail safely',async()=>{const env=environment();assert.equal((await handle(request('create-checkout','x'.repeat(65537)),env)).status,413);assert.equal((await handle(request('create-checkout','{'),env)).status,400)});
test('provider failure never fabricates a contribution or leaks details',async t=>{t.mock.method(globalThis,'fetch',async()=>{throw Error('provider-secret-value')});const env=withOrder(environment());const res=await handle(request('verify-checkout',proof()),env);assert.equal(res.status,503);assert.ok(!(await res.text()).includes('provider-secret-value'));assert.equal(env.data.has(prefix+'payment:pay_123'),false)});
